<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Dapper\" />
    <None Remove="Repository\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Dapper\" />
    <Folder Include="Repository\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Company.Domain\Company.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.36" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="6.0.36" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="6.0.29" />
    <PackageReference Include="Dapper" Version="2.1.79" />
  </ItemGroup>
</Project>
